/*
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EvlDSLRuntimeModule extends AbstractEvlDSLRuntimeModule {
}
