/*
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvlDSLStandaloneSetup extends EvlDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new EvlDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
