/*
 * generated by Xtext
 */
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ActionsUiModule extends org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui.AbstractActionsUiModule {
	public ActionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
