/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.concordance.clients.migration;

public class MigratorInstantiationException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = -6763204490238099839L;

	public MigratorInstantiationException(String message) {
		super(message);
	}	
}
