<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filesystem"
    nsURI="filesystem" nsPrefix="filesystem">
  <eClassifiers xsi:type="ecore:EClass" name="Filesystem">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drives" upperBound="-1"
        eType="#//Drive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncs" upperBound="-1"
        eType="#//Sync" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drive" eSuperTypes="#//Folder"/>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//File" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shortcut" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//File">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sync">
    <eAnnotations source="gmf.link">
      <details key="label" value="lastSync"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSync" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
