/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.hutn.exceptions;

public class HutnValidationException extends HutnException {

	// Generated by Eclipse
	private static final long serialVersionUID = 1361261707989731751L;

	public HutnValidationException(String message) {
		super(message);
	}
	
	public HutnValidationException(Throwable cause) {
		super(cause);
	}
}
