/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.flock.execute.exceptions;


public class ConservativeCopyException extends FlockRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = -6724410698885944942L;

	public ConservativeCopyException(Throwable cause) {
		super(cause);
	}
	
	public ConservativeCopyException(String message, Throwable cause) {
		super(message, cause);
	}
}
