/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.formatter;

/**
 * A Formatter provides a means for postprocessing 
 * the text generated by an EGL template. Both TemplateFactories
 * and Templates can specify a set of Formatters to
 * be used for postprocessing.
 */
public interface Formatter {

	public String format(String text);
}
