<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OO">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" ordered="false" lowerBound="1" eType="//Package" eOpposite="//Package/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotatedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" ordered="false" upperBound="-1" eType="//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" unique="false" lowerBound="1" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" ordered="false" upperBound="-1" eType="//PackageableElement" containment="true" eOpposite="//PackageableElement/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalClass" eSuperTypes="//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" ordered="false" lowerBound="1" eType="//Class" eOpposite="//Class/extendedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedBy" ordered="false" upperBound="-1" eType="//Class" eOpposite="//Class/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" ordered="false" upperBound="-1" eType="//Feature" containment="true" eOpposite="//Feature/owner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false" unique="false" lowerBound="1" eType="//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//Class" eOpposite="//Class/features"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" lowerBound="1" eType="//VisibilityEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" abstract="true" eSuperTypes="//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" ordered="false" unique="false" lowerBound="1" eType="//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false" upperBound="-1" eType="//Parameter" containment="true" eOpposite="//Parameter/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//Operation" eOpposite="//Operation/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="//StructuralFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="//StructuralFeature"/>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityEnum">
    <eLiterals name="public" value="1"/>
    <eLiterals name="private" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
</ecore:EPackage>
