/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.ide;

import org.eclipse.epsilon.examples.evl.xtext.ide.AbstractEvlDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EvlDSLIdeModule extends AbstractEvlDSLIdeModule {
}
