/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.epsilon.examples.evl.xtext.EvlDSLRuntimeModule;
import org.eclipse.epsilon.examples.evl.xtext.EvlDSLStandaloneSetup;
import org.eclipse.epsilon.examples.evl.xtext.ide.EvlDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EvlDSLIdeSetup extends EvlDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    EvlDSLRuntimeModule _evlDSLRuntimeModule = new EvlDSLRuntimeModule();
    EvlDSLIdeModule _evlDSLIdeModule = new EvlDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_evlDSLRuntimeModule, _evlDSLIdeModule));
  }
}
