/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext;

import org.eclipse.epsilon.examples.evl.xtext.EvlDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EvlDSLStandaloneSetup extends EvlDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new EvlDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
