/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext;

import org.eclipse.epsilon.examples.evl.xtext.AbstractEvlDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EvlDSLRuntimeModule extends AbstractEvlDSLRuntimeModule {
}
