/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.exceptions;

import org.eclipse.epsilon.common.module.ModuleElement;

public class EglStoppedException extends EglRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = -475729257704865019L;

	public EglStoppedException(ModuleElement ast) {
		super("out.stop() was called.", ast);
	}
}
