package org.eclipse.epsilon.egl.exceptions;

public class EglUnallocatedOutputBufferException extends EglRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = 4627578970732864067L;

	public EglUnallocatedOutputBufferException(String reason, Throwable cause) {
		super(reason, cause);
	}
}
