/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.validation;

import org.eclipse.epsilon.examples.evl.xtext.validation.AbstractEvlDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EvlDSLValidator extends AbstractEvlDSLValidator {
}
