/*
* generated by Xtext
*/
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ActionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/epsilon/eugenia/examples/executablestatemachine/textual/parser/antlr/internal/InternalActions.tokens");
	}
}
