/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.dt.extensions;

public class ExtensionLocatorException extends RuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = 8120545442816455608L;
	
	public ExtensionLocatorException(String message) {
		super(message);
	}

	public ExtensionLocatorException(String message, Throwable cause) {
		super(message, cause);
	}
}