/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.migration.execution.exceptions;

import org.eclipse.epsilon.eol.exceptions.EolRuntimeException;

public class MigrationExecutionException extends EolRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = -3550145829402258002L;

	protected MigrationExecutionException(String message) {
		super(message);
	}
	
	public MigrationExecutionException(Throwable cause) {
		this(null, cause);
	}
	
	public MigrationExecutionException(String message, Throwable cause) {
		super(message);
		initCause(cause);
	}
}
