/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.dt.traceability.editor;


public class TextLinkException extends RuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = 4995319310209878297L;
	
	public TextLinkException(String message, Throwable cause) {
		super(message, cause);
	}
}
