/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.flock.dt.emf.actions;

public class MigrationStrategyExtensionLocatorException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = 8764522300740250777L;

	public MigrationStrategyExtensionLocatorException(Exception cause) {
		super(cause);
	}
}
