package org.eclipse.epsilon.migration.dt.actions;

public class MigrationStrategyExtensionLocatorException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = 8764522300740250777L;

	public MigrationStrategyExtensionLocatorException(Exception cause) {
		super(cause);
	}
}
