/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.ui.contentassist;

import org.eclipse.epsilon.examples.evl.xtext.ui.contentassist.AbstractEvlDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EvlDSLProposalProvider extends AbstractEvlDSLProposalProvider {
}
