grammar org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.Actions with org.eclipse.xtext.common.Terminals

generate actions "http://www.eclipse.org/epsilon/eugenia/examples/executablestatemachine/textual/Actions"

Action:
	Set | Inc | Dec | If | Print;
	
Set:
	'set ' var=ID ' ' value=INT;

Inc:
	'inc ' var=ID;

Dec:
	'dec ' var=ID;

If:
	'if ' var=ID '=' value=INT;

Print:
	'print ' '"' msg=STRING '"';