/*
 * generated by Xtext
 */
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActionsRuntimeModule extends org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.AbstractActionsRuntimeModule {

}
