/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.hutn.exceptions;

public class HutnTranslationException extends HutnException {

	// Generated by Eclipse
	private static final long serialVersionUID = 8232490290734519420L;

	public HutnTranslationException(String message) {
		super(message);
	}
	
	public HutnTranslationException(Throwable cause) {
		super(cause);
	}
}
