/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.hutn.xmi;

public class HutnXmiBridgeException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = -1476988847851174120L;

	
	public HutnXmiBridgeException(Throwable t) {
		super(t);
	}
}
