/*
 * generated by Xtext
 */
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui.internal.ActionsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ActionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ActionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ActionsActivator.getInstance().getInjector(ActionsActivator.ORG_ECLIPSE_EPSILON_EUGENIA_EXAMPLES_EXECUTABLESTATEMACHINE_TEXTUAL_ACTIONS);
	}
	
}
