<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="houses" nsURI="houses" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="HousesGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="houses" upperBound="-1"
        eType="#//House" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="House">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
