<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="socialnetwork" nsURI="socialnetwork" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="SocialNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="likes" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dislikes" upperBound="-1"
        eType="#//Person"/>
  </eClassifiers>
</ecore:EPackage>
