/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.flock.execution.exceptions;


public class ConservativeCopyException extends FlockRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = -6724410698885944942L;

	public ConservativeCopyException(Throwable cause) {
		super(cause);
	}
	
	public ConservativeCopyException(String message, Throwable cause) {
		super(message, cause);
	}
}
