/*******************************************************************************
 * Copyright (c) 2009 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************
 *
 * $Id$
 */
package org.eclipse.epsilon.flock.execution.exceptions;

public class FlockUnsupportedModelException extends FlockRuntimeException {

	// Generated by Eclipse
	private static final long serialVersionUID = 4026802432275940218L;

	public FlockUnsupportedModelException(String message) {
		super(message);
	}
}
