/*
* generated by Xtext
*/
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ActionsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui.internal.ActionsActivator.getInstance().getInjector("org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.Actions");
	}
	
}
