/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.test;

import org.eclipse.epsilon.egl.IEglModule;
import org.eclipse.epsilon.egl.EglModule;
import org.eclipse.epsilon.egl.execute.context.IEglContext;
import org.eclipse.epsilon.egl.execute.context.EglContext;
import org.eclipse.epsilon.commons.parse.AST;

public class MockContext extends EglContext implements IEglContext {
	
	@Override
	public EglModule getModule() {
		return new MockModule();
	}
	
	private static class MockModule extends EglModule implements IEglModule {

		@Override
		public AST getAst() {
			return new MockAST();
		}
		
		private static class MockAST extends AST {

			// Generated by Eclipse
			private static final long serialVersionUID = -7946927850190148129L;

			@Override
			public int getColumn() {
				return 1;
			}

			@Override
			public int getLine() {
				return 1;
			}
			
		}
	}
}
