/*
* generated by Xtext
*/
package org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui.contentassist;

import org.eclipse.epsilon.eugenia.examples.executablestatemachine.textual.ui.contentassist.AbstractActionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ActionsProposalProvider extends AbstractActionsProposalProvider {

}
