/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.scoping;

import org.eclipse.epsilon.examples.evl.xtext.scoping.AbstractEvlDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class EvlDSLScopeProvider extends AbstractEvlDSLScopeProvider {
}
