<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scl" nsURI="scl" nsPrefix="scl">
  <eAnnotations source="emf.gen">
    <details key="basePackage" value="org.eclipse.epsilon.eugenia.examples"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eAnnotations source="gmf.diagram"/>
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="color" value="232,232,232"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="free"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true">
      <eAnnotations source="gmf.affixed"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eAnnotations source="gmf.link">
      <details key="source" value="from"/>
      <details key="target" value="to"/>
      <details key="label" value="name"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Port" eOpposite="#//Port/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Port" eOpposite="#//Port/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eAnnotations source="gmf.node">
      <details key="figure" value="ellipse"/>
      <details key="size" value="15,15"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//Connector"
        containment="true" eOpposite="#//Connector/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//Connector"
        eOpposite="#//Connector/to"/>
  </eClassifiers>
</ecore:EPackage>
