/*******************************************************************************
 * Copyright (c) 2008 The University of York.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.egl.test.acceptance.merge;

import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;

import org.eclipse.epsilon.common.util.FileUtil;
import org.eclipse.epsilon.egl.exceptions.EglRuntimeException;
import org.eclipse.epsilon.egl.status.ProtectedRegionWarning;
import org.eclipse.epsilon.egl.status.StatusMessage;
import org.eclipse.epsilon.egl.test.acceptance.AcceptanceTestUtil;
import org.eclipse.epsilon.egl.test.models.Model;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

// Force mergeAbsent to run before mergeAbsentNested
@FixMethodOrder(MethodSorters.NAME_ASCENDING) 
public class Merge {
	private static File StoreProgram;
	private static File GenerateProgram;
	private static File GenerateAbsentProgram;
	private static File GenerateAbsentNestedProgram;
	private static File OverwriteProgram;
	private static File DuplicatePRProgram;
	
	private static File PetOverwrite;
	private static File PetGenerate;
	private static File PetGenerateAbsent;
	private static File PetStore;
	
	private static File ExistingGenerate;
	
	private static File   ExpectedGenerate;
	private static File   ExpectedOverwrite;
	private static File   ExpectedGenerateAbsent;
	private static String ExpectedStore = "This file has not been generated by EGL.";
	
	@BeforeClass
	public static void setUpOnce() throws IOException {
		StoreProgram                = FileUtil.getFile("Store.egl", Merge.class);
		GenerateProgram             = FileUtil.getFile("Generate.egl", Merge.class);
		GenerateAbsentProgram       = FileUtil.getFile("GenerateAbsent.egl", Merge.class);
		GenerateAbsentNestedProgram = FileUtil.getFile("GenerateAbsentNested.egl", Merge.class);
		OverwriteProgram            = FileUtil.getFile("Overwrite.egl", Merge.class);
		DuplicatePRProgram          = FileUtil.getFile("DuplicateProtectedRegion.egl", Merge.class);
		
		PetOverwrite           = FileUtil.getFile("Pet_overwrite.txt", Merge.class);
		PetGenerate            = FileUtil.getFile("Pet_generate.txt", Merge.class);
		PetGenerateAbsent      = FileUtil.getFile("Pet_generateAbsent.txt", Merge.class);
		PetStore               = FileUtil.getFile("Pet_store.txt", Merge.class);
		
		ExistingGenerate       = FileUtil.getFile("Existing_generate.txt", Merge.class);
		
		ExpectedGenerate       = FileUtil.getFile("Expected_generate.txt", Merge.class);
		ExpectedGenerateAbsent = FileUtil.getFile("Expected_generateAbsent.txt", Merge.class);
		ExpectedOverwrite      = FileUtil.getFile("Expected_overwrite.txt", Merge.class);
		
		
		org.eclipse.epsilon.egl.util.FileUtil.write(PetStore,          ExpectedStore);
		org.eclipse.epsilon.egl.util.FileUtil.write(PetOverwrite,      ExpectedStore);
		org.eclipse.epsilon.egl.util.FileUtil.write(PetGenerate,       org.eclipse.epsilon.egl.util.FileUtil.read(ExistingGenerate));
		org.eclipse.epsilon.egl.util.FileUtil.write(PetGenerateAbsent, org.eclipse.epsilon.egl.util.FileUtil.read(ExistingGenerate));
	}
	
	@Test
	public void mergeStore() throws Exception {
		AcceptanceTestUtil.run(StoreProgram, Model.OOInstance);
		assertEquals(ExpectedStore, PetStore);
	}
	
	@Test
	public void mergeGenerate() throws Exception {
		AcceptanceTestUtil.run(GenerateProgram, Model.OOInstance);
		assertEquals(ExpectedGenerate, PetGenerate);
	}
	
	@Test
	public void mergeOverwrite() throws Exception {
		AcceptanceTestUtil.run(OverwriteProgram, Model.OOInstance);
		assertEquals(ExpectedOverwrite, PetOverwrite);
	}
	
	@Test (expected=EglRuntimeException.class)
	public void mergeDuplicatePR() throws Exception {
		AcceptanceTestUtil.run(DuplicatePRProgram, Model.OOInstance);
	}
	
	@Test
	public void mergeAbsent() throws Exception {
		AcceptanceTestUtil.run(GenerateAbsentProgram, Model.OOInstance);
		assertEquals(ExpectedGenerateAbsent, PetGenerateAbsent);
		
		boolean javadocWarningFound = false;
		boolean talkWarningFound    = false;
		boolean sleepWarningFound   = false;
		
		for (StatusMessage message : AcceptanceTestUtil.getStatusMessages()) {
			if (message instanceof ProtectedRegionWarning) {
				final ProtectedRegionWarning prWarning = (ProtectedRegionWarning)message;
				
				if (prWarning.getId().equals("javadoc")) javadocWarningFound = true;
				if (prWarning.getId().equals("talk"))    talkWarningFound = true;
				if (prWarning.getId().equals("sleep"))   sleepWarningFound = true;
			}
		}
		
		assertTrue("Expected warning for protected region 'javadoc'", javadocWarningFound);
		assertTrue("Expected warning for protected region 'talk'",    talkWarningFound);
		assertTrue("Expected warning for protected region 'sleep'",   sleepWarningFound);
	}
	
	@Test
	public void mergeAbsentNested() throws Exception {
		org.eclipse.epsilon.egl.util.FileUtil.write(PetGenerateAbsent, org.eclipse.epsilon.egl.util.FileUtil.read(ExistingGenerate));
		
		AcceptanceTestUtil.run(GenerateAbsentNestedProgram, Model.OOInstance);
		assertEquals(ExpectedGenerateAbsent, PetGenerateAbsent);
		
		boolean javadocWarningFound = false;
		boolean talkWarningFound    = false;
		boolean sleepWarningFound   = false;
		
		for (StatusMessage message : AcceptanceTestUtil.getStatusMessages()) {
			if (message instanceof ProtectedRegionWarning) {
				final ProtectedRegionWarning prWarning = (ProtectedRegionWarning)message;
				
				if (prWarning.getId().equals("javadoc")) javadocWarningFound = true;
				if (prWarning.getId().equals("talk"))    talkWarningFound = true;
				if (prWarning.getId().equals("sleep"))   sleepWarningFound = true;
			}
		}
		
		assertTrue("Expected warning for protected region 'javadoc'", javadocWarningFound);
		assertTrue("Expected warning for protected region 'talk'",    talkWarningFound);
		assertTrue("Expected warning for protected region 'sleep'",   sleepWarningFound);
	}
	
	
	private static void assertEquals(File expected, File actual) throws IOException {
		assertEquals(org.eclipse.epsilon.egl.util.FileUtil.read(expected), actual);
	}
	
	private static void assertEquals(String expected, File actual) throws IOException {
		Assert.assertEquals(expected, org.eclipse.epsilon.egl.util.FileUtil.read(actual));
	}
}
