<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="labels"
    nsURI="epsilon/labels" nsPrefix="epsl">
  <eClassifiers xsi:type="ecore:EEnum" name="LabelStyle">
    <eLiterals name="NORMAL"/>
    <eLiterals name="BOLD" value="1"/>
    <eLiterals name="ITALIC" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Labels">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Label" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" unique="false" eType="#//LabelStyle"
        unsettable="true"/>
  </eClassifiers>
</ecore:EPackage>
