<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="friends" nsURI="friends" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.PersonFigure"/>
      <details key="label.icon" value="false"/>
      <details key="label" value="name"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friendOf" upperBound="-1"
        eType="#//Person">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="color" value="0,255,0"/>
        <details key="source.decoration" value="arrow"/>
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enemyOf" upperBound="-1"
        eType="#//Person">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="color" value="255,0,0"/>
        <details key="source.decoration" value="arrow"/>
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
