/*
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.ide


/**
 * Use this class to register ide components.
 */
class EvlDSLIdeModule extends AbstractEvlDSLIdeModule {
}
