<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="people" nsURI="www.eclipse.org/epsilon/examples/svg" nsPrefix="p">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/org.eclipse.epsilon.eugenia.examples.svg/svg/person.svg"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
