/**
 * generated by Xtext 2.14.0
 */
package org.eclipse.epsilon.examples.evl.xtext.ui;

import org.eclipse.epsilon.examples.evl.xtext.ui.AbstractEvlDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EvlDSLUiModule extends AbstractEvlDSLUiModule {
  public EvlDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
